# Generated by Django 3.1.5 on 2021-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_insulin_macro'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
